pog=input('Digite algo: ')
print('O tipo primitivo é {}'.format(type(pog)))
print('Só tem espaços? {}'.format(pog.isspace()))
print('Só tem números? {}'.format(pog.isnumeric()))
print('Só tem letras? {}'.format(pog.isalpha()))
print('Há letras e números? {}'.format(pog.isalnum()))
print('Está tudo em maiúsculo? {}'.format(pog.isupper()))
print('Está tudo em minúsculo? {}'.format(pog.islower()))
print('Está captalizada? {}'.format(pog.istitle()))